### PR TITLE
PHP7 support

### PR DESCRIPTION
**Pull request by afk11**

### CODE REVIEW

**Comment by realpg** [comment]
Cool!

**Comment by afk11** [comment]
Not sure what the segfault in nightly is about. I'll check it out tomorrow.

**Comment by afk11** [comment]
Squashed

**Comment by afk11** [comment]
It looks like `nightly` is crashing due to a segfault after phpunit starts, but during test fixture generation (dataProviders are run before tests). I'll chase this up elsewhere, since it could be a few different things.

**Pull request merged**
